import type { StoredSurveyResponse } from "./surveyTypes";

export const mockResponses: StoredSurveyResponse[] = [
  {
    id: "mock-1",
    created_at: "2026-05-18T12:00:00.000Z",
    respondent_name: "Mock respondent",
    respondent_email: "",
    respondent_role: "Research team",
    respondent_type: "Individual",
    answers: {
      "1.1": "Develop a hybrid approach combining treaty reform and Artemis Accords principles",
      "1.2": "Moderate: add binding standards on resources, debris, supervision, and transparency",
      "3.2": "Yes, but subject to international licensing and benefit-sharing",
      "4.3": "Yes, debris-generating ASAT testing should be banned",
      "9.1": "Yes, as a separate debris obligation",
      "13.1": "Yes, endorse with clarifications",
      "13.2": ["Transparency", "Registration of space objects", "Orbital debris mitigation"],
      "14.1": ["Regulate resource extraction", "Add debris and environmental obligations", "Define and limit safety zones"],
      "15.1": "Hybrid treaty + Artemis pathway",
    },
    comments: {},
    artemis_support: "Yes, endorse with clarifications",
    selected_artemis_policies: ["Transparency", "Registration of space objects", "Orbital debris mitigation"],
    top_priorities: ["Regulate resource extraction", "Add debris and environmental obligations", "Define and limit safety zones"],
    final_recommendation: "Use a hybrid pathway with COPUOS engagement and clarified Artemis principles.",
    survey_version: "1.0",
  },
  {
    id: "mock-2",
    created_at: "2026-05-18T12:30:00.000Z",
    respondent_name: "",
    respondent_email: "",
    respondent_role: "",
    respondent_type: "Unsure / prefer not to say",
    answers: {
      "1.1": "Draft an amendment protocol to the OST",
      "1.2": "High: create new institutions for licensing, dispute resolution, and benefit-sharing",
      "3.2": "Yes, but subject to international licensing and benefit-sharing",
      "4.3": "Yes, all destructive ASAT testing should be banned",
      "9.1": "Yes, as harmful contamination",
      "13.1": "Partially, use selected principles only",
      "13.2": ["Emergency assistance", "Release of scientific data", "End-of-mission disposal planning"],
      "14.1": ["Create liability tribunal", "Mandate launch transparency", "Regulate resource extraction"],
      "15.1": "OST amendment protocol",
    },
    comments: {},
    artemis_support: "Partially, use selected principles only",
    selected_artemis_policies: ["Emergency assistance", "Release of scientific data", "End-of-mission disposal planning"],
    top_priorities: ["Create liability tribunal", "Mandate launch transparency", "Regulate resource extraction"],
    final_recommendation: "Prioritize a protocol with a practical compliance pathway.",
    survey_version: "1.0",
  },
];
